name: 'publish'

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        run: npm install -g pnpm

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        id: tauri-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'Weekly Report Assistant v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      # 准备单独的 exe 文件
      - name: Prepare exe file for release
        shell: bash
        run: |
          mkdir -p release-files
          cp src-tauri/target/release/weekly-report-assistant.exe release-files/

      # 将单独的 exe 文件上传到同一 release
      - name: Upload additional exe to the same release
        uses: softprops/action-gh-release@v2
        with:
          files: release-files/weekly-report-assistant.exe
          tag_name: ${{ steps.tauri-build.outputs.tagName }}
          draft: true
          name: ${{ steps.tauri-build.outputs.releaseName }}
          body: ${{ steps.tauri-build.outputs.releaseBody }}
          append_body: true
          token: ${{ secrets.GITHUB_TOKEN }}
